import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// One sidebar for the whole manual, autogenerated from the folder tree under
// docs/. Order comes from the numeric directory prefixes (00-, 01-, …) and each
// chapter's `sidebar_position` frontmatter — the prefixes are stripped from the
// public URLs by `numberPrefixParser` in docusaurus.config.ts, so the on-disk
// order that makes the GitHub repo readable costs nothing in the URL.
const sidebars: SidebarsConfig = {
  manual: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
